language: java
sudo: false
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --batch || true
matrix:
  include:
    - jdk: openjdk8
      dist: xenial
    - jdk: openjdk11
      dist: xenial
services:
  - docker
install:
  - mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
deploy:
  - provider: script
    script: make docker-build && make docker-push
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8
  - provider: script
    script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: b8z28tzdVU/T3Dt70JQS0Km2dca0ebmL0gGh5g/f5zYHsAzTcPZsayqUWXjJ4tq08N7OlRzx04DSDr9oCErNXSdDPOVlKf46uH3irAeUPHjCDARimRs3uGaUgYwW5X0/xpqjQrVP2YVq9+FDznKEDiULV4ztLFacv5Hx0aMwb2Q=
